### ISSUE TITLE
Importation

### ISSUE THREAD

**Issue by samspo** [pinguim06/pdf-tools-org#1] opened 2016-01-15 05:29 UTC
Nice. Thanks for this.

Importation works (just tested with a highlight with comments) but when I import I have the following things in the comments

> # +BEGIN_QUOTE
> 
> the text I highlighted 
> # +END_QUOTE
> 
> my comments

I suppose, I should just have my comments

Also, the format chosen to export is not really useful for me (difficult to read). I'd prefer something like
- [[linktopdf:page][highlights]]
  comments
  :PROPERTIES:

But I suppose, it is not so easy

**Comment by machc** [comment] 2016-01-16 16:53
Thanks for the input. That is indeed a bug in the importer. 

I am also not entirely happy with the format; it will certainly change, but I haven't decided how. The highlighted text may be huge so it doesn't feel right to make it an org heading, but "annot-1-55" is not a good heading either. @myrjola has a better formatting: https://github.com/politza/pdf-tools/pull/133#issuecomment-158753618 though not every pdf will have proper outlines.

**Comment by bugaev** [comment] 2016-02-19 22:24
Thank you for creating this useful package! I am looking forward to its further development. After testing export / import features,  I would say this project is >95% mature. The described bug seems the biggest show stopper for me. I am thinking about a situation where I edit a  pdf incrementally, saving only exported annotations, but not the pdf itself. Such a workflow is useful when a few devices are used for annotating pdfs in public archives (like http://arxiv.org), annotations are exported to org and merged. The problem is that with each export, annotations will grow by one redundant "BEGIN_QUOTE" block.
But anyways,  the described annoyance is incomparably smaller than the advantages this package gives. At the moment, filtering redundant quote blocks with external tools seems a reasonable price for convenience. I prune redundant quote blocks and blank lines using the gawk code below:

> /^\* annot/ {quotes = 0; RedundantQuote = 0; BlankLineBefore = 0}
> /^$/  {if (! BlankLineBefore) {BlankLineBefore = 1} else next}
> $0 !~ /^$/ {BlankLineBefore = 0}
> /^#\+BEGIN_QUOTE/ {if (quotes > 0) { RedundantQuote = 1; }}
> /^#\+END_QUOTE/ {if (! RedundantQuote) {print}; quotes = quotes + 1; RedundantQuote = 0;  next }
> (! RedundantQuote) {print}

This almost solves my problems with multiple exports/imports. The remaining issues are:
- Slightly changing :color: property. For example, #fefe00 --> #fdfd00
- Changing :modified: property, but this is probably normal.

**Comment by machc** [comment] 2016-10-30 04:50
I believe this fixes the bug: https://github.com/machc/pdf-tools-org/commit/ba7e0c0a10c1c30a3f8468765ec371776f91fa96

**Closed as completed by machc** 2016-10-30 04:50 UTC
